site_name: CroMesh Dokumentacija
site_description: Dokumentacija za CroMesh mreÅ¾u i Meshtastic konfiguraciju
site_author: CroMesh zajednica
site_url: https://docs.cromesh.eu
nav:
  - ğŸ  Uvod: index.md
  - âš™ï¸ Postavke: postavke.md
  - ğŸ“¡ Odabir ureÄ‘aja: odabir-ureÄ‘aja.md
  - ğŸ“¶ Antene: antenne.md
  - ğŸ“± Aplikacije: aplikacije.md
  - ï¿½ firmware: firmware.md
  - ï¿½ Solarni UreÄ‘aji: solarni-ureÄ‘aji.md
  - ï¿½ MQTT: mqtt.md
  
theme:
  name: material
  language: hr
  features:
    # --- Navigation behavior ---
    - navigation.collapse     # make sections collapsible
    - navigation.expand       # auto-expand current section
    - navigation.indexes      # make parent sections clickable (Detaljnije/index.md)
    - navigation.sections     # group related pages
    - navigation.instant
    - navigation.footer
    # --- Content enhancements ---
    - content.tabs
    - content.sections
    - content.code.copy
    # --- Search & TOC ---
    - search.suggest
    - search.highlight
    - toc.integrate

  palette:
    scheme: slate
    primary: green
    accent: dark-green

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - footnotes
  - nl2br
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search:
      lang: en   # 'hr' not supported yet
   

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cromesh
    - icon: fontawesome/brands/github
      link: https://github.com/CroMesh
    - icon: material/web
      link: https://cromesh.eu
  generator: false
